--- #ec2 AMI to create basic ami 
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Basic Provisioning of AMI from an instance
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-05658a34e12accb4c
      wait: no
      name: myami
      tags:
        Name: MyAMI
        Service: TestAMIService
    register: instance
